### ISSUE TITLE
Exporting message on toast notification during export action disappears after 8 seconds

### ISSUE THREAD

**Issue by qatoolist** [RedHatInsights/subscription-central-ui#35]
Ref.: 
https://issues.redhat.com/browse/TEAMNADO-2585

Env.: Stage/beta

**Comment by joeldmyers** [comment]
I am unable to replicate this on stage or locally. Note that it is expected behavior for this loading alert to disappear the moment the manifest has been exported (which often takes less than 8 seconds).  In QA I have been using a user with manifests that take longer to export, and I confirmed that it did not disappear until the success notification appeared.

**Comment by joeldmyers** [comment]
This behavior is expected. The story was updated to clarify the AC.
